PROJECT ON UNEMPLOYEMENT OF INDIA DATA ANALYSIS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\Users\neelg\Downloads\unemployeementinindia.csv")
df.head()

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Area
0,Andhra Pradesh,31-05-2019,Monthly,3.65,11999139.0,43.24,Rural
1,Andhra Pradesh,30-06-2019,Monthly,3.05,11755881.0,42.05,Rural
2,Andhra Pradesh,31-07-2019,Monthly,3.75,12086707.0,43.50,Rural
3,Andhra Pradesh,31-08-2019,Monthly,3.32,12285693.0,43.97,Rural
4,Andhra Pradesh,30-09-2019,Monthly,5.17,12256762.0,44.68,Rural

In [ ]:
print(df.shape)
print(df.dtypes)
print(df.ndim)

(768, 7)
Region                                          str
 Date                                           str
 Frequency                                      str
 Estimated Unemployment Rate (%)            float64
 Estimated Employed                         float64
 Estimated Labour Participation Rate (%)    float64
Area                                            str
dtype: object
2

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Region                                    740 non-null    str
 1    Date                                     740 non-null    str
 2    Frequency                                740 non-null    str
 3    Estimated Unemployment Rate (%)          740 non-null    float64
 4    Estimated Employed                       740 non-null    float64
 5    Estimated Labour Participation Rate (%)  740 non-null    float64
 6   Area                                      740 non-null    str
dtypes: float64(3), str(4)
memory usage: 42.1 KB

In [ ]:
df.describe()

,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%)
count,740.000000,7.400000e+02,740.000000
mean,11.787946,7.204460e+06,42.630122
std,10.721298,8.087988e+06,8.111094
min,0.000000,4.942000e+04,13.330000
25%,4.657500,1.190404e+06,38.062500
50%,8.350000,4.744178e+06,41.160000
75%,15.887500,1.127549e+07,45.505000
max,76.740000,4.577751e+07,72.570000

In [ ]:
df.isnull().sum()

Region                                      28
 Date                                       28
 Frequency                                  28
 Estimated Unemployment Rate (%)            28
 Estimated Employed                         28
 Estimated Labour Participation Rate (%)    28
Area                                        28
dtype: int64

In [ ]:
print(df.isnull())

     Region   Date   Frequency   Estimated Unemployment Rate (%)  \
0     False  False       False                             False
1     False  False       False                             False
2     False  False       False                             False
3     False  False       False                             False
4     False  False       False                             False
..      ...    ...         ...                               ...
763    True   True        True                              True
764    True   True        True                              True
765    True   True        True                              True
766    True   True        True                              True
767    True   True        True                              True

      Estimated Employed   Estimated Labour Participation Rate (%)   Area
0                  False                                     False  False
1                  False                                     False  False
2                  False                                     False  False
3                  False                                     False  False
4                  False                                     False  False
..                   ...                                       ...    ...
763                 True                                      True   True
764                 True                                      True   True
765                 True                                      True   True
766                 True                                      True   True
767                 True                                      True   True

[768 rows x 7 columns]

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

Region                                      0
 Date                                       0
 Frequency                                  0
 Estimated Unemployment Rate (%)            0
 Estimated Employed                         0
 Estimated Labour Participation Rate (%)    0
Area                                        0
dtype: int64

In [ ]:
df.loc[0]
df.tail(7)

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Area
747,West Bengal,31-12-2019,Monthly,7.24,11335696.0,45.97,Urban
748,West Bengal,31-01-2020,Monthly,7.27,11208617.0,45.39,Urban
749,West Bengal,29-02-2020,Monthly,7.55,10871168.0,44.09,Urban
750,West Bengal,31-03-2020,Monthly,6.67,10806105.0,43.34,Urban
751,West Bengal,30-04-2020,Monthly,15.63,9299466.0,41.20,Urban
752,West Bengal,31-05-2020,Monthly,15.22,9240903.0,40.67,Urban
753,West Bengal,30-06-2020,Monthly,9.86,9088931.0,37.57,Urban

In [ ]:
df